### ISSUE TITLE
Problem of timeout with Multi-threaded backend server

### ISSUE THREAD

**Issue by Julienh** [bottlepy/bottle#1015]
Hello,

Since long time I have a problem when I use Bottle with Multi-threaded server: randomly I have a long request answer or a timeout.
- The code is simple, just load some data from a database.
- I tried with Python 3.2 and now Python 3.6.2
- I tried Debian 7 and 9
- I use the last version of Bottle
- I tried cherrypy and now paste

If someone have an idea how to fix my problem, thank you :)

**Comment by kianxineki** [comment]
What server are you using?

**Comment by defnull** [comment]
Bottle does not do anything fancy that would cause a request to hang or timeout. Thread and IO handling is done by the server backend (cherrypy/paste), not bottle itself. Bottle only blocks if the socket hangs while reading the request body, and that is caused by a slow or unresponsive client (or an overloaded server backend).

Try to increase thread-pool sizes in your server backend, try another one (uwsgi?) and make sure that your client actually sends the entire request, even if an error response is sent early. Clients that stop sending data but keeping the connection open for whatever reasons are misbehaving and will cause timeouts as you have seen.

**Comment by Julienh** [comment]
Thank you for your answer, I will try your advices
