### ISSUE TITLE
Bottle redirect does not call function

### ISSUE THREAD

**Issue by Xenonheat** [bottlepy/bottle#1045]
When using bottle's redirect command it raises and exception.
Because of this, the function associated with the URI does not get called.
Is there a workaround for this. Could not find an associated issue.

**Comment by defnull** [comment]
The exception is of type `HTTPResponse` which shortcuts the execution of the current function and causes bottle to send an empty response to the client with the correct redirect status code and location header. The client then sends a new request to the path specified in the `redirect()` function call. This is how client-side redirects work in HTTP.

Simply do not catch the exception and let bottle handle it.

**Comment by Xenonheat** [comment]
Thanks, I understand that part.
What I am having problems with is the sending of a new request.
It seems that the requested URI's associated function is called every other time I do that redirect.
If you can help me understand how that part works, I would really appreciate it.

**Comment by defnull** [comment]
Let's assume you have two routes in your app:

    @route('/foo')
    def foo():
        redirect('/bar')

    @route('/bar')
    def bar():
        return "Hello World"

If a browser requests `/foo`, then `foo()` is called in your app which simply calls `redirect('/bar')`. This throws an `HTTPResponse` exception which in turn causes bottle to send a response to the client with status code `303 See Other` and the `Location: /bar` header.
The browser receives this response, and since it is a good browser it follows the redirect and sends a new request to `/bar` as specified by the `Location` header in the previous response.
This new response will trigger `bar()` in your app, which returns "Hello World" which is then displayed in the browser.

On server side, you will see two requests: One for `/foo` immediately followed by a second request for `/bar`. This is because redirects work client-side, not server-side. It's the browsers job to send a second request after it receives a `303 See Other` response.

Did that help you? If not, please provide an example of what your app looks like, what behavior you'd expect and what behavior your are seeing instead.
