### ISSUE TITLE
pep8 style

### ISSUE THREAD

**Issue by zongzhenh** [bottlepy/bottle#1050]
Hi, guys

I found some code style problem (reference pep8) from `bottle.py` file, I want to fix it and make `bottle.py` more pretty~

**Comment by defnull** [comment]
Please do, but I had to decline some pep8 pull requests in the past for certain reasons:

- I'll only merge a pull request if the majority of edits actually enhances readability or at least does not hurt it. pep8 is only a recommendation, and sometimes violating pep8 is better than following it blindly. 
- That said, please do not use automated tools to pep8ify the whole file and commit it all without review. These tools are often too strict and reduce readability instead of enhancing it. Some pep8 violations in bottle.py are intentional.
- Try to keep individual commits small and focused on a specific part of bottle.py. Commits with hundreds of edits across the entire file are hard to merge with git and are annoying if you try to `git-blame` a codebase.

**Comment by zongzhenh** [comment]
Thank for your awesome advice, I am very agree with you.
The pull requests https://github.com/bottlepy/bottle/pull/1051, CI was passed, please review~

**Comment by defnull** [comment]
Merged. Thanks
