### ISSUE TITLE
Redirect Bug?

### ISSUE THREAD

**Issue by ehouarn-perret** [bottlepy/bottle#1066]
I tried many redirect but nothing work, every time I have exceptions even on the simplest api design.
Example: redirecting to the 404 (also tried with home/index or root "/") resource on 404 error:
```
<h1>Critical error while processing request: /ssdf</h1><h2>Error:</h2>
<pre>
Location: http://localhost:5555/404
Content-Type: text/html; charset=UTF-8

</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;C:\Users\ehoua\Desktop\Github\EhouarnPerret.Python.MVCBottle\project\libs\bottle.py&quot;, line 1104, in wsgi
    out = self._cast(self._handle(environ))
  File &quot;C:\Users\ehoua\Desktop\Github\EhouarnPerret.Python.MVCBottle\project\libs\bottle.py&quot;, line 1057, in _cast
    self.default_error_handler)(out)
  File &quot;C:\Users\ehoua\Desktop\Github\EhouarnPerret.Python.MVCBottle\project\routes\error.py&quot;, line 8, in on_error404
    return redirect(&#039;/404&#039;)
  File &quot;C:\Users\ehoua\Desktop\Github\EhouarnPerret.Python.MVCBottle\project\libs\bottle.py&quot;, line 2810, in redirect
    raise res
project.libs.bottle.HTTPResponse

</pre>
127.0.0.1 - - [21/May/2018 06:30:53] "GET /ssdf HTTP/1.1" 500 897
```

**controllers/mvc/errors.py**
```
from project.libs.bottle import redirect
from project.helpers.metadata import extended_template


def not_found():
    return extended_template(inner_template='error404.html')
```

**routes/error.py**
```
from project.controllers.mvc.errors import not_found
from project.libs.bottle import redirect
from runserver import app


@app.error(404)
def on_error404(error):
    return redirect('/404')


@app.get('/404')
def error404():
    return not_found()
```

My resource on 404 works but redirecting to it or to index/home/whatever always trigger an exception and the redirection does not seem to occur.

Do you have any why this kind of behavior can happen?

**Comment by ehouarn-perret** [comment]
Update:

I have a working solution with:
```
@app.error(404)
def on_error404(error):
    response.status = 303
    response.set_header('Location', '/404')
```

**Comment by defnull** [comment]
Yes, that works. 

To explain: Error handlers are a 'last resort' and exceptions thrown from error handlers will not be processed by bottle anymore, because otherwise a failing 500-error handler would result in an infinite recursion. But `redirect()` is implemented by raising a `HTTPResponse` exception and thus cannot be used from within an error handler. Another solution would be to catch the exception thrown by `redirect()` and simply return it. Or just call and return `not_found()` instead of triggering a redirect and another request from the client.
