### ISSUE TITLE
request.query gets gibberish if GET or POST param contains UTF-8 encoded strings

### ISSUE THREAD

**Issue by danny0838** [bottlepy/bottle#1085]
Currently `request.query` gets gibberish if GET or POST param contains UTF-8 encoded strings.

Patching the following line in `bottle.py`:

    from urllib.parse import urlencode, quote as urlquote, unquote as urlunquote
    urlunquote = functools.partial(urlunquote, encoding='latin1')

to (i.e. remove the second line):

    from urllib.parse import urlencode, quote as urlquote, unquote as urlunquote

fixes the issue.

**Comment by defnull** [comment]
The `Request.query` property returns a `FormsDict` which stores the keys and values in their raw binary form. Note that URLs are, per standard, binary strings and do not have an encoding attached. There is no guarantee that these are actually utf8 encoded.

Since python3 strings are unicode, we use the `latin1` codepage to decode binary data into unicode strings, because `latin1` is lossless and can be re-encoded later. This is also the same approach the WSGI PEP-3333 spec took for any binary input in python 3 environments.

`FormsDict` allows convenient attribute-access (instead of dict-like item access) to get values re-coded with UTF8, and also has a `FormsDict.decode()` method that returns a new dict with all values re-coded.

See https://bottlepy.org/docs/dev/api.html#bottle.FormsDict

**Comment by danny0838** [comment]
I get it. Thank you.

**Comment by mfaizsyahmi** [comment]
@defnull the documentation is not clear. Can you give me a snippet on how to get utf-8 encoded dict? I tried `bottle.request.query.decode()`, `bottle.request.query.decode(encoding="utf8")`, and `bottle.request.query.decode(encoding="latin1")` but get the same gibberish every time.

**Comment by defnull** [comment]
Not sure what's unclear in the docs (e.G. https://bottlepy.org/docs/dev/api.html#bottle.FormsDict ). If `bottle.request.query.whatever` (dot-lookup) or `bottle.request.query.decode()["whatever"]` (decode all) returns gibberish, then make sure the client actually sends UTF8 in the first place.

The WSGI spec (PEP-3333) mandates that the query string (and other types of data too) MUST be decoded with `latin1` by the WSGI server, because the WSGI server cannot know the actual encoding and `latin1` is reversible. Bottle will re-encode this with `latin1` to get the original byte string again, then decode that with the configured encoding (utf8 by default). If you get junk out of that, it means that either your WSGI server does not conform to spec, or that the client did not sent utf8, or that there is something wrong in how your application handles or displays that data.
