### ISSUE TITLE
Why not assume that all use functools?

### ISSUE THREAD

**Issue by jmcaine** [bottlepy/bottle#1101]
In get_undecorated_callback(), a bit of work is done to extract the callback.  I'm wondering why self.callback.__name__ isn't returned and users simply be required to use functools.wraps.

?

**Comment by defnull** [comment]
Because the name attribute was not present in earlier versions of python that were supported by bottle (I think). Also, why not? `functools.wraps` adds another line and is inconvenient to use. If we can guess the correct name with high probability and no negative impact if we fail, then it's fine to do these extra steps for the users convenience.
