### ISSUE TITLE
Unable to use json with accented characters

### ISSUE THREAD

**Issue by zeraphin21** [bottlepy/bottle#1116]
Hi,
I have bottle v0.12.16.
I run a simple server to handle json send by a simple curl.
But the bottle.request.json is not able to work with accented characters.
Here is the code :
```
#!/usr/bin/env python3
import bottle

@bottle.post("/say")
def post_say():
    data = bottle.request.json
    print(data)
    return "OK"
bottle.run(bottle.app(), host='0.0.0.0', port=12800, debug= True, reloader=True)
```

To use it, curl request :
curl --header "Content-Type: application/json" --request POST --data "{\\"phrase\\":\\"test without special characters\\",\\"lang\\":\\"fr\\"}" http://localhost:12800/say     => OK
curl --header "Content-Type: application/json" --request POST --data "{\\"phrase\\":\\"test with àéèù\\",\\"lang\\":\\"fr\\"}" http://localhost:12800/say     => KO

Error is :

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 16: invalid continuation byte

**Comment by defnull** [comment]
Json text [must](https://www.ietf.org/rfc/rfc4627.txt) be unicode, and defaults to `utf-8`. Your operating system or shell seems to default to a different encoding and encodes sone of these non-ascii characters as `0xe9`, which is not a valid input for `utf-8`. The error message is quite precise, actually: The input is invalid json, because it contains bytes that cannot be decoded as `utf8`.

Make sure your shell uses an utf-8 enable locale, or you will have the same problem when defining form values, cookies or headers with curl that contain non-ASCII characters.
