### ISSUE TITLE
bottle + gunicorn + meinheld errors when having concurrency

### ISSUE THREAD

**Issue by agalera** [bottlepy/bottle#1131]
I have used this combination for a long time, always behind a nginx serving static and I have not had problems, but now I have needed to serve a file from bottle (basically in a test environment) and I realized that if I make calls to the file static works correctly, but if I make several requests at the same time, the static file never responds.

I start the server like this:
```python
if __name__ == "__main__":
    run(
        port=3322, host="0.0.0.0",
        server="gunicorn",
        worker_class='egg:meinheld#gunicorn_worker',
        workers=16,
        # reloader=True,
        quiet=False,
        debug=True
    )
```

I attached some images in case I did not explain myself well:
https://imgur.com/a/JrgoDEm
![Imgur](https://i.imgur.com/F6Rp9gO.png)
![Imgur2](https://i.imgur.com/wdSfTGn.png)
![Imgur3](https://i.imgur.com/qci5yEb.png)

I have tried other combinations in case my code was wrong and it worked correctly:
gunicorn + gevent
gunicorn + sync
gunicorn + gthreads
meinheld without gunicorn
for now, it has only happened to me in the static files, maybe because they are loaded later?

**Comment by defnull** [comment]
Bottle is a WSGI framework and relies on a well-behaving multi-threaded runtime. Three assumptions must be true at all times:

* A `threading.local` container must be local to the current thread.
* A WSGI request is handled by the same thread from start to finish.
* Two WSGI requests are not handled by the same thread at the same time. 

If you replace traditional threads by e.g. 'green threads' then you also have to monkey-patch either bottle or `threading.local` or thread locals like `bottle.request` will break. I suspect that this is the issue here.
