### ISSUE TITLE
getting HTTP_AUTHENTICATION key missing with custom auth middleware

### ISSUE THREAD

**Issue by mandrewstuart** [bottlepy/bottle#1136]
Hey team, I am a long time fan of bottle and this is my first issue - so thank you.

I inherited a contract with the front end that relies on the header: {'authentication': 'bearer TOKEN'}, where TOKEN is a session token. I am getting the unexpected error:

```File "/home/stress_test/.local/lib/python3.6/site-packages/bottle.py", line 1984, in __getitem__
    return tonat(self.environ[self._ekey(key)], 'latin1')
KeyError: 'HTTP_AUTHORIZATION'
```

Do you know why? Could you please help me sort it out?

Thank you,
Andrew

**Comment by carc1n0gen** [comment]
A KeyError usually means the key does not exist in the dictionary.  I don't think you need the `HTTP_` prefix

**Comment by mandrewstuart** [comment]
I am not checking for it. I check for the `authentication` key

**Comment by carc1n0gen** [comment]
`authentication` isn't a standard header.  Maybe you mean `authorization`?

**Comment by mandrewstuart** [comment]
Yes, sorry, I was replying from a bar. Back at my computer right now

**Comment by carc1n0gen** [comment]
At this point I would print the headers dictionary to see what keys exist

**Comment by mandrewstuart** [comment]
pprint(dict(request.headers)) yields:
```
{'Accept': 'application/json',
 'Authorization': 'Bearer '
                  'd1205034-fa2c-4c5e-80e3-bc789349eee5c0383fe5-bc78-4b66-9f80-f15be1a07dba',
'Connection': 'close',
 'Content-Length': '115',
 'Content-Type': 'application/json; charset=utf-16',
 'Host': 'localhost:8707'}
```

**Comment by defnull** [comment]
The WSGI standard is based on good old CGI and headers are stored with an `HTTP_` prefix and uppercase in the `environ` dict. This is why bottle searches for `HTTP_AUTHORIZATION` if you lookup the `Authorization` header. If you get a KeyError, than the header is not present.

**Comment by mandrewstuart** [comment]
We were having trouble with simultaneous requests. I'm 98% sure we were attaching the 'authorization' header.

**Comment by defnull** [comment]
WSGI is synchronous (one request per thread) and bottle uses thread-local storage (`threading.local`) to reference the request and response parameters during a request. If you are using a server or framework that employs a different kind of concurrency (e.g. gevent, greenlets, ...) then you must take special care to either:

a) Monkey-patch `threading.local` before importing bottle, so bottle understands this new kind of concurrency. This is easy to do with `gevent` or servers that are based on `gevent`. 
b) Or not use any function during a request that interacts with greenlets. This unfortunately includes reading from a socket (e.g. the request body) with some serverimplementations in some configurations, if this socket instance was replaced with a greenlet-aware alternative.

Otherwise, if you for example read from a greenlet-enabled socket (by reading the request body), and the read IO would block, it blocks the greenlet and not the thread. The greenlet loop will schedule a different request to be handled on the same thread, without telling bottle it did so. If `threading.local` is not patched, then bottle will mix up the parameters fro these requests and hard-to-debug errors happen.

Might this be the case here?

**Comment by mandrewstuart** [comment]
Thank you! That sounds like it is exactly what was happening.

**Comment by mandrewstuart** [comment]
For the next person with this issue, this is the first problem I have ever faced with bottle and by using an authentication mechanism in the post body, instead of the header, it works like a charm. I have a post-only API even for reads which of course isn't RESTful - but that really doesn't bother me.

**Comment by agalera** [comment]
@mandrewstuart if you're interested, I made a plugin a long time ago for bottle to use jwt, maybe it will be useful

https://github.com/agalera/bottlejwt

**Comment by mandrewstuart** [comment]
Thanks @agalera I appreciate your reaching out. I find JWTs to be a lot of overhead so I don't typically use them. Also, the project I ran into trouble with using the 'authorization' header, I don't have the freedom to change the authorization mechanism as there are too many moving parts.
