### ISSUE TITLE
nohup SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gongel** [bottlepy/bottle#1170]
I run my py code like "python unit_lbs_debug.py"  and it is no problem, but I use nohup command like this 'nohup python unit_lbs_debug.py &' and it met error like below.
`Traceback (most recent call last):
  File "unit_lbs_debug.py", line 3, in <module>
    from bottle import route, run, request, get, post, static_file, template
  File "/home/disk3/gongel/web/bottle.py", line 675
    __hook_reversed = {"after_request"}
                                      ^
SyntaxError: invalid syntax`

[Error picture](https://github.com/gongel/DemoWeb/blob/master/error.png)

System: CentOS 6.3
Python: Python 2.7.3
Bottle: 0.13-dev

**Comment by defnull** [comment]
Python 2.7.3 support was dropped after the most used distributions shipping it went out of support: Ubuntu 12.4LTS (precise) and Debian 7 LTS (wheezy) are both EOL by now.

CentOS 6 is in maintenance-mode since may 2017 and will stop providing security updates in about a year. Python 2 will be dead even before that (1.1.2020). I strongly suggest upgrading to a more recent version, both OS and Python wise.

Oh, and the most recent CentOS 6 release is 6.10, not 6.3. There might even be an acceptable python version available directly from the distribution.
