### ISSUE TITLE
Auto json/JSONPlugin should detect lists/tuples

### ISSUE THREAD

**Issue by avladev** [bottlepy/bottle#1180]
When `autojson=True` bottle detects only dictionaries which are converted to JSON and proper header is set. May be this same behavior should be true for both lists and tuples.

**OS:** Linux Mint 19.1 Tessa
**Bottle:** 0.12.17

**Test**
```python
from threading import Thread
from time import sleep
from unittest import TestCase

import requests
from bottle import Bottle, run

# https://github.com/bottlepy/bottle/blob/0dd195111621b4db5e9b7d5e5852fab3c6270098/bottle.py#L2011
app = Bottle(autojson=True)


@app.get('/dict')
def dict_view():
    return {'result': 1}


@app.get('/list')
def list_view():
    return ["result"]


@app.get('/tuple')
def tuple_view():
    return "result",


t = Thread(target=lambda a: run(app=a), args=(app,))
t.daemon = __name__ != "__main__"
t.start()

url = 'http://127.0.0.1:8080'


class AutoJSONTestCase(TestCase):
    @classmethod
    def setUpClass(cls):
        # Wait for web-server to start
        sleep(1)

    def test_dict(self):
        response = requests.get(url + '/dict')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.headers.get('Content-Type'), 'application/json')
        self.assertEqual(response.text, '{"result": 1}')
        pass

    def test_list(self):
        response = requests.get(url + '/list')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.headers.get('Content-Type'), 'application/json')
        self.assertEqual(response.text, '["result"]')

    def test_tuple(self):
        response = requests.get(url + '/tuple')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.headers.get('Content-Type'), 'application/json')
        self.assertEqual(response.text, '["result"]')

```

**Comment by defnull** [comment]
A REST API should never return lists (JSON arrays) directly, without a surrounding object. There were several security problems related to arrays in the past, and it is considered bad practice for semantic reasons as well. If you are designing your own API, avoid raw lists. Return an object with some context and a `results` field or something similar. If you are implementing an existing API and do not have a choice, you have to do the JSON part yourself for these routes. The JSONPlugin does not really do anything special. It just sets a `Content-Type` and returns the result of `json.dumps(data)`. That can be done in two extra lines of code without the plugin.

**Comment by n1ngu** [comment]
I understand those two extra lines of code might not be worth reopening the discussion, but for the record Flask dropped their equivalent security feature preventing raw lists JSON serialization.

Rationale was: browsers vulnerable to raw JSON lists are:
- are ancient legacy with rare usage, so only applications still supporting those should be concerned about this. The bulk of framework users don't need to be worried nor warned about it.
- are vulnerable to worse RCE exploits, so it's not like this feature can provide any safety to such browsers

See:
- https://flask.palletsprojects.com/en/latest/security/#json-security
- https://github.com/pallets/flask/issues/248
- https://github.com/pallets/flask/pull/1671

Also, I can't agree on the point about semantics. For paginated item lists, wrapping response data with a pagination object is a must, but for small item lists a raw list is way more semantic than the widespread`{"d": [actual-data]}` practice. I feel this practice was widely adopted due to the past relevance of the exploits it prevented, but stayed out of FUD.

That said, I am not pushing for any change in bottle.py, just wanted to note here that this feature is confusing, outdated, somewhat undocumented and definitely not saving any children.
