### ISSUE TITLE
HTTP POST: ResourceWarning: unclosed file <_io.BufferedRandom name=36>

### ISSUE THREAD

**Issue by mcr-ksh** [bottlepy/bottle#1206]
There is a resource leek that I cannot determine from my code. I guess it's from bottle. 

```
Bottle v0.12.18 server starting up (using WSGIRefServer())...
Listening on http://irsdev:5000/
Hit Ctrl-C to quit.
```

On Fileupload (via tracemalloc):
> /devel/anaconda3/envs/asdf/bin/bottle.py:1672: ResourceWarning: unclosed file <_io.BufferedRandom name=36>
>   def fset(self, value): ls.var = value
> Object allocated at (most recent call last):
>   File "/devel/anaconda3/envs/asdf/lib/python3.7/tempfile.py", lineno 622
>     newline=newline, encoding=encoding)

Function:
```
@route('/api/<threshold:float>', method='POST')
def func(threshold=0.5):
```

Command:
curl -X POST -F 'file=@/tmp/pic.jpg' http://irsdev:5000/api/0.5

**Comment by x-yuri** [comment]
At some point you probably access `request.body`. And if the body is too big it puts it into a [temporary file][1] (opens a file). From what I can see you're responsible for closing the file. Unless you do, you get the warning. Such warnings are displayed only in [debug mode][2]. To get more lines of traceback, run it with `PYTHONTRACEMALLOC=N`, where `N` is the desired number of lines of the traceback.

[1]: https://github.com/bottlepy/bottle/blob/0.12.18/bottle.py#L1176
[2]: https://github.com/bottlepy/bottle/blob/0.12.18/bottle.py#L2538

**Comment by defnull** [comment]
Turns out using `NamedTemporaryFile` instead of `TemporaryFile` fixes the `ResourceWarning` in most cases because `NamedTemporaryFile` (indirectly) implements `__del__` to explicitly close (and remove) the file. This is not needed for `TemporaryFile` because these are unlinked immediately, which is why these are still technically 'open' when the garbage collector collects the file, which in turn triggers the warning.

Only downside is that on a hard crash, a temporary file may remain on disk, so this is not an ideal solution. Deprecating a `request.body` that lives longer than the request and switching back to `TemporaryFile` might be the cleaner option. Until then, I'll consider this fixed (in master). I'll keep one of the related issues open.

**Comment by tobi1220** [comment]
I know that this is old, but for anyone who stumbles upon this: even if you're not directly accessing `request.body` but rather referencing your uploaded file with `request.files.get("NAME").file` , you still need to close the body with `request.body.close()`, otherwise you'll also get this warning.
