### ISSUE TITLE
include() in template fail if have space between "include" and "("

### ISSUE THREAD

**Issue by RimeOCRLIB** [bottlepy/bottle#1258]
Unfortunately Bottle have a bag in include () function 
```
% include ("my_template.tpl")  # template not found
% include("my_template.tpl")  # template found
```
the only difference it is space after "include" is forbidden
Hope this issue message will help somebody save time in debugging

**Comment by defnull** [comment]
This is already fixed in `master`. `include` and `rebase` were keywords in `0.11` and change to being normal functions starting with `0.12`. In `0.12` the old syntax is still supported, but it will yield a deprecation warning. The first version is interpreted as a keyword and is translated to `include('("my_template.tpl")')` which is wrong, obviously.
