### ISSUE TITLE
static_file is serving gzipped files as uncompressed

### ISSUE THREAD

**Issue by jmlrt** [bottlepy/bottle#1350]
When using [`static_file`](https://github.com/bottlepy/bottle/blob/71bb933649ba009cd537c2e973519d6e024c02a2/bottle.py#L2842) without `mimetype` to serve a file compressed with gzip, bottle seems to uncompress it on the fly.

How to reproduce it:

1. create a gzipped text file:
```shell
$ echo 'Hello, world!' > hello
$ gzip hello
```

2. serve the file with and without `mimetype`:
```python
>>> from bottle import route, run, static_file
>>> @route("/static/<filename:path>")
... def send_static(filename):
...     return static_file(filename, root=".")
...
>>> @route("/mimetype/<filename:path>")
... def send_static_with_mimetype(filename):
...     return static_file(filename, root=".", mimetype="application/x-gzip")
...
>>> run(host="localhost", port=8080, debug=True)
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.
```
3. in a second shell, download the file using both endpoint and check its type:
```python
>>> import requests
>>> import os
>>> def dl_file(type):
...     url = f"http://localhost:8080/{type}/hello.gz"
...     response = requests.get(url)
...     path = type
...     if not os.path.exists(path):
...         os.makedirs(path)
...     else:
...         os.remove(f"{path}/hello.gz")
...     open(f"{path}/hello.gz", "wb").write(response.content)
...     os.system(f"file {path}/hello.gz")
... 
>>> dl_file("static")
static/hello.gz: ASCII text
>>> dl_file("mimetype")
mimetype/hello.gz: gzip compressed data, was "hello", last modified: Wed Sep 15 08:29:37 2021, from Unix, truncated
```

**Comment by defnull** [comment]
The file is not decompressed by bottle, but if the file-name looks stream-compressed (e.g. `foo.txt.gz`), bottle sets the `Content-Encoding` header in addition to `Content-Type` and most HTTP clients will decompress the body automatically. Not sure if that was a good idea in hindsight. HTTP is a mess sometimes. If you want to serve gzip files as is, you must explicitly set the mimetype parameter to bypass mime-guessing.

**Comment by jmlrt** [comment]
Hi @defnull, thanks for the quick answer and explanation. 

>bottle sets the Content-Encoding header in addition to Content-Type and most HTTP clients will decompress the body automatically.

Indeed `requests` is uncompressing the file while wget isn't which made me confused a lot 😄. 

>If you want to serve gzip files as is, you must explicitly set the mimetype parameter to bypass mime-guessing.

To be able to serve gzip and non-gzip files in the same route without `Content-Encoding`, detecting files mimetype and passing it to `static_file` seems fine:
```python
from bottle import route, run, static_file
import mimetypes

@route("/static/<filename:path>")
def send_static(filename):
    mimetype = mimetypes.guess_type(filepath)
    return static_file(filename, root=".", mimetype=mimetype)
```

Do you think it could make sense to add a new param to `static_file` to be able to disable setting the `Content-Encoding`?

**Comment by octaprog7** [comment]
The problem is in one additional (Content-Encoding) and one different content (Content-Type) response header.
![bottle_bug_ed](https://user-images.githubusercontent.com/14124236/148029519-63918c1d-f5b2-4586-9308-55aed06548a8.png)
[download_file.txt](https://github.com/bottlepy/bottle/files/7806301/download_file.txt)

**Comment by octaprog7** [comment]
When calling the bottle.static_file function with the default mimetype value (True), the mimetypes.guess_type (filename) function is called, which incorrectly determines the mime type of the file content. But it correctly determines what the file is encoded (compressed) with.
Then the 'Content-Encoding' header is set to gzip, the 'Content-Type' header somewhere before is set to "text / html; charset = UTF-8".
When downloading a file, based on the response headers, the client concludes that it is gzip-compressed, text / html in UTF-8 encoding, and automatically unpacks it (requests module).

To prevent this from happening (the easiest way), you need to prohibit the call to mimetypes.guess_type (filename), since it incorrectly determines the mime type of the file. The python-magic / libmagic module could be used, but this contradicts the words "micro web-framework" in the definition of bottle at http://bottlepy.org/docs/dev/.
To do this, you need to remove the default value (= True) from the mimetype parameter of the bottle.static_file function. Thus, the user will have to manually set this parameter.
![guess_bad_pic](https://user-images.githubusercontent.com/14124236/148189173-3b16a331-682f-4e61-808e-9ea9d754551a.png)
![guess_bad](https://user-images.githubusercontent.com/14124236/148189197-36762a09-db87-4b02-831a-f32eff34a28b.png)

**Comment by octaprog7** [comment]
Perhaps I found a solution for the mimetype is True parameter in static_file (..). You need to change the code in static_file to the code highlighted in the picture. Content-Type is forced to application/octet-stream.
This change on the server side tells the client downloading the file that the data type of the file is unknown. The client does not unpack the file!
![app_octet_stream](https://user-images.githubusercontent.com/14124236/148213949-10417f95-1323-459f-bbfd-f20c012884cc.png)
![bug_deleted](https://user-images.githubusercontent.com/14124236/148214401-0cdca2e5-f122-4560-9068-9dd2d98fbe23.png)
