### ISSUE TITLE
A bit of confusion about the resetting the view function

### ISSUE THREAD

**Issue by 0Jvang** [bottlepy/bottle#1353]
Hello, I have recently read the source code of Bottle to learn more about Web development. I would like to discuss with you some doubts about the resetting view function when the plugin is updated.  
You override the instance attribute `call` through the descriptor attribute of the Route class, but why use the descriptor?  A simple implementation I can think of would be for `call` not to be defined as a descriptor but as an instance method, and to reset the view function directly overload it with `self.__dict__['call']=self._make_callback() `

**Comment by defnull** [comment]
Some magic functions (e.g. `__call__` or `__len__`) are baked into the class structure for performance reasons and cannot be replaced at runtime. This is a not so well known implementation detail of the CPython interpreter. Methods also have (or had) a slight overhead compared to unbound callables.This is why instead of defining `__call__` or a method that calls something replaceable, the `Route` class has a `cached_property` that holds the fully wrapped callable and can ne directly called from the router.

Or in short: Because of CPython shenanigans and it's also faster.
