### ISSUE TITLE
documentation: special methods: OPTIONS

### ISSUE THREAD

**Issue by drandreaskrueger** [bottlepy/bottle#1367]
**Why?** LibreOffice `=WEBSERVICE()` before `GET` always calls `OPTIONS` and `HEAD` first.

**Solved:** Now, to get rid of the `405 error`, I only had to add `method=['GET', 'HEAD', 'OPTIONS']`, like this

    @route("/my-endpoint", method=['GET', 'HEAD', 'OPTIONS'])

which is obvious _now_, but I had not been able to find it in the documentation ...

**Suggestion:** perhaps add OPTIONS to [special methods](https://bottlepy.org/docs/dev/tutorial.html#http-request-methods).

---

Huge thanks for `bottle` by the way, using it often, since testing it to be [the best, back then](https://github.com/drandreaskrueger/pythonMicroframeworks/blob/master/README.md) (warning: **OUTDATED**!).

**Comment by defnull** [comment]
`OPTIONS` is not handled in any special way by bottle. `HEAD` and `ANY` are special, but `OPTIONS` is just a normal HTTP method you have to explicitly bind to, if you need that. It is more important nowadays because of CORS mechanics, but CORS is  best handled in a middleware or `before_request` hook anyway. Then you would not have to worry about that anymore.
