### ISSUE TITLE
Can I use bottle with python 2.7.5 on hostmonster?

### ISSUE THREAD

**Issue by tim042849** [bottlepy/bottle#1379]
FYI: I am an old (don't knock old, consider the alternative), retired web developer and I just want to have fun in my golden years - not do anything fancy. I currently lease a hostmonster shared server and I don't really see a need to upgrade at this time. Hostmonster uses centOS for shared servers and provides only python2 (currently 2.7.5). Sudo is not available. Since bottle is just one file, I presume that all I would need to do is upload bottle.py to my server. I would welcome any and all comments, caveats or warnings. 

The project I have in mind would be just a simple portal to pdf files with a simple access hierarchy. It could be updated vi FTP and would not need a database. Documentation and comments in bottle.py indicate compatibility with 2.7.5. Thanks

**Comment by Jwink3101** [comment]
What you asked:

I believe it should work. I work just test with a simply “hello world” before investing too much. However, you need to do it via the very-antiquated CGI interface. 

What you didn’t:

Regardless of your age, it’s worth learning python3. Especially on a *new* project! You may as well start with that as a base since it won’t be too hard, especially compared to porting. 

And if your host doesn’t support it, your host is providing end-of-life software and you should vote with your wallet

**Comment by tim042849** [comment]
I actually do use python3, but not on hostmonster. Apparently python2 is a default on the version of centOS used by hostmonster and I imagine that python3 will be available as they upgrade to a centOS that has python3 as a default. That's shared hosting for you and I have no other reason to upgrade (an unnecessary vote with my wallet). From [Jwink3101](https://github.com/Jwink3101) looks like I should be able to do a proof-of-concept prototype with python2 and if I want to go from there, I will use the AWS account that I recently set up. I can't imagine that I would ever need anything more than their Free Tier. Now that is voting with a flat wallet.:)
Thanks very much for the feedback. Have a great day.
