### ISSUE TITLE
Optional routing parameters with default values

### ISSUE THREAD

**Issue by dcelasun** [bottlepy/bottle#372]
Consider the hello world example:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from bottle import route, run
@route('/hello/<name>')
def index(name='World'):
    return '<b>Hello %s!</b>' % name

run(host='localhost', port=8080)
```

If I leave the `<name>` part empty, it gives out an 404 error. Is it possible to have it default to "World"?

**Comment by yedderson** [comment]
I'm building an API and passing parameters over the URL. Some of the parameters are optional and can be omitted (ex: /api/element/123/optional_parm/1). I don't like to repeat myself for every URL combination. 
As of now, would it be possible to get this working using only one route ?

**Comment by eric-wieser** [comment]
What's your objection to using:

```python
 @route('/api/element/<a>/<optional_param>/<b>')
 @route('/api/element/<a>/<b>')
def handler(a, b, optional_param):
    pass
```

**Comment by iurisilvio** [comment]
@yedderson this issue is really old and I don't even know why it is still open. It was just a question.

If you want only one definition, you can use something like `/api/element/<your_path:path>` and parse `your_path` the way you want, but I suggest you define all your routes and fallback to this option only if you have a complex use case.

**Comment by yedderson** [comment]
@eric-wieser there is many optional params
@iurisilvio that would make it.
