### ISSUE TITLE
static_file() throws away response headers

### ISSUE THREAD

**Issue by bbradshaw** [bottlepy/bottle#580]
Trying to figure out why this toy code wasn't working:

```
@app.route('/')
def get_basic_file():
        response.set_cookie('basic_cookie', 1)
    return static_file('index.html', 'path')
```

It seems the static_file() method never looks at the original response object.

**Comment by camconn** [comment]
I looked around in the bottle docs, and the `BaseResponse.set_cookie` behavior is well defined.

However, `static_file` is only documented in bottle.py right now, and has no reference in the docs even though it's used several times.

```python
# Starting at line 2460
def static_file(filename, root,
                mimetype='auto',
                download=False,
                charset='UTF-8'):
    """ Open a file in a safe way and return :exc:`HTTPResponse` with status
        code 200, 305, 403 or 404. The ``Content-Type``, ``Content-Encoding``,
        ``Content-Length`` and ``Last-Modified`` headers are set if possible.
        Special support for ``If-Modified-Since``, ``Range`` and ``HEAD``
        requests.
        :param filename: Name or path of the file to send.
        :param root: Root path for file lookups. Should be an absolute directory
            path.
        :param mimetype: Defines the content-type header (default: guess from
            file extension)
        :param download: If True, ask the browser to open a `Save as...` dialog
            instead of opening the file with the associated program. You can
            specify a custom filename as a string. If not specified, the
            original filename is used (default: False).
        :param charset: The charset to use for files with a ``text/*``
            mime-type. (default: UTF-8)
    """

    ...
```

This definitely needs to be added to the docs though.

**Comment by birlorg** [comment]
It's in the docs now, and as of version 0.12.19 this still happens.

a fix, in static_file, replace the `headers=dict()` line with `headers=response.headers`

That will solve this issue.

**Comment by defnull** [comment]
This behavior is 'by design' and documented. [static_file()](https://bottlepy.org/docs/dev/api.html#bottle.static_file) returns a [HTTPResponse](https://bottlepy.org/docs/dev/api.html#bottle.HTTPResponse) and that "overrides changes made to the global response object" and "bypasses error handlers". The idea is to have a clean and self-contained way to completely define how the response should look like, and not to worry about the state of the global response object at that time. The correct approach is to manipulate the returned object as you already figured out. Changing that *now* would be a breaking change unfortunately.
