### ISSUE TITLE
Accept unicode keys in ConfigDict.load_dict

### ISSUE THREAD

**Issue by jenmontes** [bottlepy/bottle#720]
I was recently trying to follow the JSON file example in the [loading configuration from a nested `dict`](http://bottlepy.org/docs/dev/configuration.html#loading-configuration-from-a-nested-dict) documentation, but I ran into a `TypeError`.

It turns out that JSON files loaded with `json` from the standard library have `unicode` keys (whereas using the `simplejson` module will result in `str` keys). Trying to load a dictionary with `unicode` keys into the configuration with `load_dict` will raise a `TypeError`.

I was able to fix this locally by making sure `load_dict` would accept either `str` or `unicode` as keys and making sure `__setitem__` would convert Unicode keys to bytes (so there wouldn't be a mix of `str` and `unicode` keys in the configuration).

**Comment by avelino** [comment]
Great, their share will be very welcome!

**Comment by jenmontes** [comment]
I'd be happy to submit a PR for this, but I'm not sure if it's better to force `unicode` keys to become `str` in `ConfigDict.__setitem__`, or if I should leave them as Unicode (so there will possibly be a mix of `unicode` and `str` keys in the configuration).

**Comment by goodmami** [comment]
Just ran into this myself. Like @jenmontes, I'm also wondering if we need to coerce `unicode` keys to be byte strings. The code currently has if-statements like these:

```python
if isinstance(key, str):
    ...
```

But in Python3, `str` is the same as `unicode` in Python2, so I can "fix" this problem by running the app with Python3. Unless ConfigDict keys really need to be bytes, why don't we use `basestring` (Python3 doesn't have `basestring`, but Bottle defines it as a compatibility measure). The code would thus become:

```python
if isinstance(key, basestring):
   ...
```

There are 3 places in ConfigDict where this change would be necessary (`load_dict()`, `update()`, and `__setitem__()`).

**Comment by defnull** [comment]
I would force "native" string keys by de-coding unicode in python2 (`tonat()`), and rejecting byte strings in python3. In code this means:

  if isinstance(key, (str, unicode)):
    key = tonat(key)

This way, runtime lookups with native strings is always fast. Now that I think about it, an `sys.intern` call on keys would not harm either.

**Comment by goodmami** [comment]
Thanks for the input. I tried all of your suggestions, but in the end went with my original fix. Here's why:

* `isinstance(key, basestring)` is equivalent to using `isinstance(key, (str, unicode))` based on the values Bottle uses for `basestring`, `str`, and `unicode` in both py2 and py3 (or please explain if I'm wrong about this)
* `tonat()` caused problems with key lookup. Basically, the key is converted when a value is set, but not converted when it is retrieved. Alternatively, we could override `get()` and `__getitem__()` and run `tonat()` each time they're called, as well, but I think that will harm rather than help performance
* `sys.intern()` is not available for Python2

It looks like ConfigDict is available from release-0.12, so I created a pull request for both that release (#776) and master (#777).

Let me know if there's anything else I can do.

**Comment by defnull** [comment]
Your second point is a good one: Better to error-out on byte keys in python3 than silently converting stuff and provoke random KeyErrors later.

Thanks for the pull requests, they are perfect :)

**Comment by goodmami** [comment]
Thanks for the feedback! I wasn't sure if I was following the contributor guidelines correctly.
Also, thanks to @jenmontes for the original bugfix description.
