### ISSUE TITLE
Add json property for 'application/json-rpc' requests

### ISSUE THREAD

**Issue by kromkrom** [bottlepy/bottle#769]
Don't know if there are any pitfalls, but seems to be trivial:
`if ctype in ['application/json', 'application/json-rpc']:`
instead of
`if ctype == 'application/json':`

**Comment by defnull** [comment]
If I remember #616 and understand [1] correctly, browsers white-list allowed content types for cross origin requests (instead of black-listing). So accepting ``application/json-rpc`` should not have any security implications. Right?

[1: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by kromkrom** [comment]
Yes, it seems it makes no difference

**Comment by oz123** [comment]
@defnull, since you merged #773, I guess this issue can be closed.
