### ISSUE TITLE
make requires Python 2.5

### ISSUE THREAD

**Issue by andreas-roehler** [bottlepy/bottle#780]
Running make failt w/ the following:

python2.5 test/testall.py
make: python2.5: Kommando nicht gefunden
make: *** [test_25] Fehler 127

####

Maybe not hard-code the Python version?

**Comment by defnull** [comment]
There is no "make && make install" because bottle does not need to be built. make without a target runs "make release" because that happens to be the first rule in the Makefile. A release needs to test against supported python versions including 2.5. You can run "make test" if you want to test against the system python version only.
