### ISSUE TITLE
Unable to mount to path containing variable

### ISSUE THREAD

**Issue by bchbchbch** [bottlepy/bottle#793]

**Comment by brhsiao** [comment]
So, I tried modifying the signature of `mountpoint_wrapper` to `def mountpoint_wrapper(*args, **kwargs)`. Then I chased the call stack down to `Bottle._handle`, which overwrites `bottle.raw_path` with `PATH_INFO`, which holds the local path. I changed this to save the raw path:

```python
def _save_base_path(self, environ):
    if 'bottle.base_path' not in environ:
        if 'bottle.raw_path' in environ:
            environ['bottle.base_path'] = environ['bottle.raw_path']

def _handle(self, environ):
    self._save_base_path(environ)
    path = environ['bottle.raw_path'] = environ['PATH_INFO']
    # rest of function...
```

Moving down in `_handle`, I found

```python
route, args = self.router.match(environ)
```

which I chased down to `Router.match`. It seems to grab the `PATH_INFO`, so I added

```python
base_path = self._get_base_path(environ)
```

This is where I get stuck. The router appears to split routes between static and dynamic paths, which is determined from the moment you call `app.route`. Digging into `Router.add` et al it seems like building this in will be a hell of a refactoring job.

Am I wrong? Can someone more acquainted with the code tell me if this just isn't possible/worth it?

**Comment by RonRothman** [comment]
Hi Brandon,

Is it not sufficient to put the parameter in the route (as opposed to in
the mount point)?

bottle.mount('/users', app)

@app.get('/<user_id>')
def index(user_id):
    return user_id

**Comment by brhsiao** [comment]
Sure! But doesn't that sort of defeat the purpose of mounting subapps?

**Comment by RonRothman** [comment]
No, I don't think it does.  Wouldn't it still useful be to decompose an app
this way, say?

bottle.mount('/users', user_app)
bottle.mount('/
​projects​
',
​project
_app)

@
​user_​
app.get('/<user_id>')
def index(user_id):
    return user_id

@project_app.get('/<project_id>')
def index(project_id):
    return project_id
​...
​

**Comment by brhsiao** [comment]
It feels to me the top two benefits of subapps are (1) subapp-specific plugins and (2) not having to type the mount point over and over. In the case of mounting `/users/<user_id:int>`, I might e.g. write a plugin that fetches the user based on the user ID, aborts if it's not found, and pass the user instead of the user ID to the function. I'd want to mount that *specifically* to `/users/<user_id:int>`, and not have to use a decorator over and over. And having to write `<user_id:int>` repeatedly is not only clunky but arguably a violation of DRY.

Your example doesn't really capture the pain point of this "bug" as each of your mounted apps only has one endpoint, but once you have to manually add `users/<user_id:int>/messages`, `/users/<user_id:int>/hobbies`,  `/users/<user_id:int>/fetishes`, and ten others, you start getting uneasy.

**Comment by RonRothman** [comment]
Thanks for the explanation.  After mulling it over, I suppose I find your
first two benefits unconvincing.  (1) You can install plugins at the app
level without having to specify a decorator repeatedly.  (2) You can create
the mount points programmatically if you won't want to repeat the literal
"<user_id:int>".

I do find your third point more apt--but since I've never designed an app
with that particular structure, I'm afraid I can't really speak to the use
case.  Good luck!
-ron

**Comment by brhsiao** [comment]
Sorry, I explained badly. For (1), say I have an endpoint `/users`. I might have user-specific endpoints like `/users/<user_id>/friends` and `/users/<user_id>/messages`. I might also have generic user-related endpoints, like `/users/get-graph` and `/users/do-something`. If I installed a plugin, all four endpoints would get it, but I only want it on the first two. Is that possible?

For (2), wow, somehow I hadn't thought of that. Thanks.

**Comment by team-python** [comment]
From my view the logic for mounting with a variable in the mount point does not seem to really fit. 
To me it seems an app should be independent of the mount point, and not require recoding to work at different mount points.  If there is a variable in the mount point, then every route handler is receiving a an additional parameter not contained in the route itself?
To me this does not read well, and does not extend to the case where an app is in a separate file.

However I do sympathise with you having to tyle   '/<user_id:int>/mesage'   '/<user_id:int>/hobies'  etc each time.

I made a filter that may be of some help.  It allow for multiple choice.  It is designed for file name, but would work for your case.
you could have:

      @get('<user_id:int>/<function:fileExt:message,hobbies,fetishes')
      def userFuncs(user_id,function):
          ...

Not sure if it helps, but if it does I will post the code.

**Comment by adnanoner** [comment]
Hi @innov8ian , would be interested in some extra code with an example 👍
