### ISSUE TITLE
Is bottle.py ok for production?

### ISSUE THREAD

**Issue by meatballcoder** [bottlepy/bottle#827]
Is bottle.py ok for production?

**Comment by andyxning** [comment]
As far as i know, [Shinken](https://github.com/naparuba/shinken), which is now seems not actively developed, use it in production before.

**Comment by RonRothman** [comment]
To be frank: you can't ask a question like that and expect to receive a meaningful answer. The answer is, as it always is with broad questions, "it depends."

To illustrate, I'll tell you my experience. I have used Bottle in production to successfully serve many hundreds of requests per second, with no trouble. I have also used it (in a different application) to serve thousands of requests per second, and while it did work, the server's performance eventually became unacceptable, and the source of the problem turned out to be Bottle. (We discovered this after profiling the application, and when we switched from Bottle to Falcon, that particular bottleneck disappeared.)

So: it depends.

FYI in the system where Bottle did not scale well to thousands of QPS, we eventually traced the problem to the interaction between `Bottle` and `gevent`, particularly the use of thread-local storage.

Good luck!

**Comment by andrealmar** [comment]
http://www.magazineluiza.com.br is one of the biggest e-commerce retailers in Brazil. 
They use Bottle in production.
