### ISSUE TITLE
Using Jinja2Template produces deprecation warnings

### ISSUE THREAD

**Issue by mgedmin** [bottlepy/bottle#888]
Using code like this
```python
@app.get('/hello')
def hello():
    return template('hello.html', template_adapter=bottle.Jinja2Template)
```
causes a deprecation warning to be emitted:
```
.../bottle.py:3325: DeprecationWarning: Absolute template path names are deprecated.
  fname = self.search(name, self.lookup)
```

**Comment by xiaket** [comment]
@defnull I bumped into this issue today and took a look into it. I might be wrong but I don't think this commit provides the best option.

In @mgedmin 's example, a filename is provided, and during the `__init__` of `Jinja2Template` class, this name is used to find the filename using `search` method defined in `BaseTemplate` class. So far, so good.

Later on, in the `prepare` phase of the template, the filename(now is the full path to the file) is provided to the env object in the `Jinja2Template` instance to look for a template(again), and the lookup function used the `loader` method defined in `Jinja2Template` class, which in turn, will call the `search` method again, and finally cause the problem.

@mgedmin 's commit just avoided this problem by passing `self.name`(instead of `self.filename`) to the lookup function, which will do the search again. But this is not really optimal. Instead, I suggest we should find some way to do an early return in the loader function, to avoid the second search.

**Comment by xiaket** [comment]
meanwhile, I'm using the code below to make the warning go away:

```
import bottle

def loader(kls, name):
    import os
    fname = name if os.path.isfile(name) else kls.search(name, kls.lookup)
    if not fname: return
    with open(fname, 'rb') as f:
        return f.read().decode(kls.encoding)

bottle.Jinja2Template.loader = loader
```

If this looks good to you, I'm happy to prepare another pull request for this.
