### ISSUE TITLE
different behavior using the server meinheld

### ISSUE THREAD

**Issue by kianxineki** [bottlepy/bottle#896]
Gevent and meinheld are behaving differently, I think the right would be to meinheld according to the description of the class,  I do not even look like the most comfortable.

https://github.com/bottlepy/bottle/blob/master/bottle.py#L1865
    """ A thread-local subclass of :class:`BaseResponse` with a different
        set of attributes for each thread. There is usually only one global
        instance of this class (:data:`response`). Its attributes are used
        to build the HTTP response at the end of the request/response cycle."""

Gevent test:

``` python
from gevent import monkey; monkey.patch_all()
from bottle import post, request, run
import requests


@post('/ok/<correct>')
def ok(correct):
    print("[0] value: %s correct value: %s" % (request.json['number'], correct))
    requests.post("http://httpbin.org/post", json={'number': 99})
    print("[1] value: %s correct value: %s" % (request.json['number'], correct))


@post('/test')
def test():
    pass
run(host='0.0.0.0', port=9988, server='gevent')
```

```
[0] value: 0 correct value: 0
[0] value: 2 correct value: 2
[0] value: 3 correct value: 3
[0] value: 4 correct value: 4
[0] value: 5 correct value: 5
[0] value: 6 correct value: 6
[0] value: 7 correct value: 7
[0] value: 1 correct value: 1
[0] value: 9 correct value: 9
[0] value: 8 correct value: 8
[1] value: 6 correct value: 6
[1] value: 0 correct value: 0
[1] value: 2 correct value: 2
[1] value: 3 correct value: 3
[1] value: 4 correct value: 4
[1] value: 5 correct value: 5
[1] value: 9 correct value: 9
[1] value: 8 correct value: 8
[1] value: 7 correct value: 7
[1] value: 1 correct value: 1
```

meinheld test:

``` python
from meinheld import patch
patch.patch_all()
from bottle import post, request, run
import requests


@post('/ok/<correct>')
def ok(correct):
    print("[0] value: %s correct value: %s" % (request.json['number'], correct))
    requests.post("http://httpbin.org/post", json={'number': 99})
    print("[1] value: %s correct value: %s" % (request.json['number'], correct))


run(host='0.0.0.0', port=9988, server='meinheld')
```

```
[0] value: 0 correct value: 0
[0] value: 1 correct value: 1
[0] value: 3 correct value: 3
[0] value: 5 correct value: 5
[0] value: 2 correct value: 2
[0] value: 6 correct value: 6
[0] value: 4 correct value: 4
[0] value: 7 correct value: 7
[0] value: 8 correct value: 8
[0] value: 9 correct value: 9
[1] value: 9 correct value: 0
[1] value: 9 correct value: 7
[1] value: 9 correct value: 1
[1] value: 9 correct value: 5
[1] value: 9 correct value: 2
[1] value: 9 correct value: 6
[1] value: 9 correct value: 3
[1] value: 9 correct value: 4
[1] value: 9 correct value: 8
[1] value: 9 correct value: 9
```

test:

``` python
import requests
import threading


def call(number):
    print("call %s" % number)
    requests.post('http://localhost:9988/ok/%s' % number,
                  json={'number': number})


threads = []
for x in range(10):
    t = threading.Thread(target=call, args=(x, ))
    t.start()
    threads.append(t)

for x in threads:
    x.join()

```

**Comment by defnull** [comment]
Looks like ``meinheld.patch.patch_all()`` does not patch ``threading.local`` to be gevent-aware. ``gevent.monkey.patch_all()`` does that.

**Comment by methane** [comment]
FYI, please don't use `monkey.patch_all()` unless you're very detailed about whole libraries
you're using and you can investigate your troubles by yourself.

Without `monkey.patch_all()`, Bottle, requests and meinheld works fine.

**Comment by defnull** [comment]
Okay, here is a summary:

Meinheld calls WSGI applications synchronously (one request per thread, one thread per request) during normal operation, and works fine with bottle (or any other WSGI app). Before and after the WSGI request is handled, though, all network IO is done via greenlets.

It stops working if you use greenlet features from within the WSGI application. If a greenlet blocks, it suspends the current greenlet and allows another greenlet to run _in the same thread_. Meinheld may start handling a new request in the same thread, while the old request is still in progress. Now we have two requests that are running in the same thread.

This causes bottle to mix-up the thread-local contexts, because it expects to be run in a normal, thread-based environment. In normal threading, context switches within the same thread are impossible.

Calling `meinheld.patch.patch_all()` replaces the stdlib `socket` module with a greenlet-based version that does not block the current thread, but the current greenlet instead. Other than `gevent` for example, the `meinheld` patching is incomplete though. It patches sockets only. Calls like `time.sleep()` or reading local files still blocks the thread, not the greenlet. Also, `threading.local` is not patched, causing the issues with bottle.


*tl,dr*: You changed the concepts of threading and did not tell bottle about it ;)

**Comment by kianxineki** [comment]
For what I am understanding, I can use meinheld without using patch_all(). It would behave like a fully synchronous server but it would work without problems.

Seems like a good plan, I just have to start up more processes of bottle + meinheld
