### ISSUE TITLE
Httptools a new Httpparser with Uvloop

### ISSUE THREAD

**Issue by Benozo** [bottlepy/bottle#939]
this is not an Issue but rather a request for  Httptools support with Uvloop.

Uvloop is in 0.13.dev0, I ran a simple bench on it and its way faster then gevent.

will httptools with uvloop and asyncio be integrated into bottle python3+?

**Comment by Benozo** [comment]
HttpTools+Uvloop+Wsgi #940

**Comment by defnull** [comment]
Your performance benefits should be mostly attributes to httptools, since the gevent server adapter is written in python and httptools is a C extension. Did you compare it to uWSGI?

A solid WSGI adapter for asyncio based event loops would be nice, and httptools is a great library to speed up raw HTTP parsing performance, but please note that this stack won't solve the 10K problem (which is the main benefit of gevent, by the way). WSGI was designed as a synchronous protocol. Reading from `enciron['wsgi.input']` is expected to block and there is no standard way around that. WSGI does not know about coroutines and has no way to yield and wait for events from an event loop.  So sum it up: WSGI is thread-bound. 10K clients require 10K threads. This does not mix well with the single-thread never-block approach of asyncio.

**Comment by Benozo** [comment]
@defnull  Apologies for the late reply, so i did a test against Uwsgi and the httptools intergration was still faster by upto 5-15% gain on static content . However when testing it against a DB backend (RethinkDB) HttpTools Integration seems to fail miserably while UWSGI becomes much faster. Not sure why this happens tho.
