### ISSUE TITLE
"AttributeError: 'PseudoInputFile' object has no attribute 'buffer'" while attempting to export to CGI.

### ISSUE THREAD

**Issue by csharpemcee** [bottlepy/bottle#950]
`Traceback` (most recent call last):
  File "C:\path-to-my-app\webapp.py", line 18, in <module>
    app.run(server='cgi')
  File "C:\...\Scripts\bottle.py", line 755, in run
    run(self, **kwargs)
  File "C:\...\Scripts\bottle.py", line 3127, in run
    server.run(app)
  File "C:\...\Scripts\bottle.py", line 2750, in run
    CGIHandler().run(fixed_environ)
  File "C:\...\lib\wsgiref\handlers.py", line 519, in __init__
    self, sys.stdin.buffer, sys.stdout.buffer, sys.stderr,
AttributeError: 'PseudoInputFile' object has no attribute 'buffer'`

**Comment by defnull** [comment]
Looks like you are trying to run this script in an IDLE shell, but IDLE does not provide a real shell. The `wsgiref.CGIHandler` breaks because `PseudoInputFile` does not provide an attribute a normal file object would.

So, this is either a bug/shortcoming of IDLE or wsgiref. We cannot fix this in bottle. Your best change is to test your CGI script outside of IDLE (or not use CGI, if that is an option. CGI is slow, old and not recommended).
