### ISSUE TITLE
remove or replace the beaker session middleware example in recipes

### ISSUE THREAD

**Issue by keredson** [bottlepy/bottle#961]
It's borked, no longer maintained, etc.  At minimum, its [save function](https://github.com/bbangert/beaker/blob/8d08358873fcdb8e63cb215e5b19a150f3e7855d/beaker/session.py#L435) writes the entire session at once, clobbering other changes make in other HTTP requests to unrelated keys.

It existing in bottle's documentation is an implicit endorsement, and it's leading Bottle users astray.  It should not be used in production web applications that could ever make concurrent web requests.

Split off from here: https://github.com/bottlepy/bottle/issues/591#issuecomment-289492800

**Comment by defnull** [comment]
I think adding a warning would be enough, since there are no real alternatives other than not using sessions at all and switching to a database. 

Something along the lines: "If two concurrent requests modify the same session at the same time, one of the updates might get lost. For this reason, sessions should only be populated once and treated as a read-only store after that. If you find yourself updating sessions regularly, and don't want to risk loosing any updates, think about using a real database instead."

**Comment by keredson** [comment]
A warning isn't bad, but it's weird to offer a read/write API only to them say "don't use it". 

You're right alternatives are lacking.  We wrote our own replacement last summer because of this.  (Our site gets a few million uniques a month - not huge but not nothing for production testing.).   https://github.com/keredson/drsession if interested as an alt option. Safe for concurrent writes of different keys.

**Comment by dagnelies** [comment]
Well, I made a lil' plugin here:

https://github.com/dagnelies/canister

it's pretty simple and provides "in-memory" sessions. Since parallel requests basically reference the same data object, it should even be fine in most cases. 

...the gotcha: it's in memory, hence not suited for large data / long-term sessions / huge traffic. But for average use cases, it's just fine. 😄
