### ISSUE TITLE
How bottle can send list as parameter in get request?

### ISSUE THREAD

**Issue by trangtv57** [bottlepy/bottle#966]
If i have list as [0,1,3,4,1] how can i use get request to send it, and how can i get this list to handle like print list, or sort list, something like this. Thanks you.

**Comment by defnull** [comment]
If you pass the same key multiple times, you can get all values via `bottle.request.query.getall('param')`. Example: `http://example.copm/form?list=1&list=2&list=3`

In `requests`, you would do that by passing a list of tuples (instead of a dict) to the `params` keyword argument. Its poorly documented but it works: `request.request(url, params=[('list', value) for value in values])`.

**Comment by trangtv57** [comment]
thank you more guys.
