### ISSUE TITLE
How to use : (colon char) in route url?

### ISSUE THREAD

**Issue by yn-coder** [bottlepy/bottle#976]
How to use : (colon char) in route url?

I have simple Bottle route, and URL should contain `:` (colon) sign. URL should be like `/REST/item:128` or `/REST/item:89753`

My route is

    @route('/REST/item:<id:int>')
    def icc(id):
        return { 'id': id }

Route is not working properly. id contain only last char from url id, not full id (`8` for `/REST/item:128`).

How to use `:` (colon char) in route properly?

**Comment by yn-coder** [comment]
Some discussion at SO

https://stackoverflow.com/questions/44378155/how-to-use-colon-char-in-bottle-route

**Comment by yn-coder** [comment]
Seems like some error in routing

**Comment by defnull** [comment]
Bottle currently supports two syntaxes for url wildcards: The `<new>` one (since 0.10) and the `:old` syntax. Both are described here: http://bottlepy.org/docs/dev/routing.html

In your example, the `:` triggered the old syntax. The solution is to escape the colon with a backslash (as described in the SO answer). Escaping is fully implemented and works as intended, but is undocumented. This is why I leave this issue open. Pull requests for better documentation would be welcomed.
