### ISSUE TITLE
Enable cors on 401 responses

### ISSUE THREAD

**Issue by leiserfg** [bottlepy/bottle#978]
If I use 

```python
@hook('before_request')
def enable_cors():
    response.headers['Access-Control-Allow-Origin'] = '*'
```
All routes works with CORS, but when a view aborts v.g: `return abort(401, 'Access denied, incorrect user or password')` the headers are not added to the response.

```
Content-Length:747
Content-Type:text/html; charset=UTF-8
Date:Thu, 15 Jun 2017 19:50:49 GMT
Server:WSGIServer/0.2 CPython/3.5.3rc1
```

**Comment by pepelisu** [comment]
I think this is the way decorators work. If an error occurs inside the decorated function it will stop and the decorator will not be called. 
``abort`` only calls to ``raise HTTPerror`` so execution is stopped and error is presented. 
When the error is raised, it seems that bottle handles it by simply returning the error page with the traceback (if using default error pages). That means that the response object is not what you expect, but a new response object with nothing else that the error. 
I am not sure that it is a bug. Otherwise, if you add some sensible information to the response, and despite the error bottle still construct your response object then that information will be visible for example by non authorized requests. 
For me make sense, but maybe @defnull thinks different.

**Comment by defnull** [comment]
Returning `HTTPResponse` (or `HTTPError`, or using `abort()`, or raising an exception) will overwrite whatever was set on the global `response` object. This is intentional. You usually do not want headers or cookies to leak into error responses if you `abort()` a request because of an error or exception.

Simply bind your cors-handler to `after_request` instead of `before_request` if you want to send this header no-matter-what.
