### ISSUE TITLE
`FormsDict` documentation

### ISSUE THREAD

**Issue by kuraga** [bottlepy/bottle#991]
`FormsDict` documentation [says](http://bottlepy.org/docs/dev/api.html#bottle.FormsDict):

>  Attributes are automatically de- or recoded to match `input_encoding` (default: `‘utf8’`)

> decode(encoding=None)
> Returns a copy with all keys and values de- or recoded to match `input_encoding`. Some libraries (e.g. WTForms) want a unicode dictionary.

* "to match `input_encoding`" or "to match `encoding` or (`input_encoding` if `None`)"?
* "de- or recoded to match" or "de- or recoded to match if `recode_unicode` is `True`, unmodified else"?
* there is a special case in [code](https://github.com/bottlepy/bottle/blob/master/bottle.py#L2193) - `bytes` - what about it?

> getunicode(name, default=None, encoding=None)
> Return the value as a unicode string, or the `default`.

* do you mean "`unicode`/`str`" at "unicode string"?
* "de- or recoded to match `encoding` (`input_encoding` if `None`)" have to be added? or "de- or recoded to match `encoding` (`input_encoding` if `None`) if `recode_unicode` is `True`, unmodified else"?
* there is a special case in [code](https://github.com/bottlepy/bottle/blob/master/bottle.py#L2193) - `bytes` - what about it?

Thoughts (IMHO):

* `getunicode` + "unicode string" is ambiguous. Well, maybe it wasn't for Python 2 period... But it's not a Unicode string in fact.
* is `recode_unicode` needness in public API?
* Let's write these docs more clearly?.. :smile: 
* Couldn't we parse (using `input_encoding`) headers *initially*? Then `recode_unicode` and `encoding` arguments are needless...

Thanks!

**Comment by kuraga** [comment]
Updated

**Comment by defnull** [comment]
Most HTTP request attributes (headers, request path, form values) are bytes in nature don't have encoding information attached. The web server cannot reliably detect the encoding and only the application knows which encoding is used. This is why WSGI does not decode these values for you, but keeps them in their original form.

In Python 2, this is simple: All strings are byte-strings anyway, so you have do decode them in your application.
In Python 3, WSGI uses unicode in most places. Because it cannot detect the correct encoding, byte strings are decoded using 'latin1', which is a byte-preserving encoding. You can re-encode with 'latin1' and get the original bytes back.

This is exactly what `FormsDict` does for your. You specify the application-specific encoding in `input_encoding`, which defaults to `utf8`. In Python 2, `FormsDict` decodes the WSGI byte-strings to unicode using this encoding. In Python 3, it has to re-encode these strings, because they were decoded with 'latin1' already, which is wrong in most cases. You can disable this re-encoding with `recode_unicode=False` but there is no real reason to do this, as long as your WSGI backend conforms to the spec. 

So, in the docstrings, the phrase "de- or recoded" or the explicit mention of "unicode strings" is used because Bottle supports both Python 2 and 3 at the same time, and has do do different things based on the Python version. Most of your confusion originates from that, I think. Whenever you can pass an encoding to a function, it overrides the instance-level `input_encoding` default. 

> getunicode + "unicode string" is ambiguous. Well, maybe it wasn't for Python 2 period... But it's not a Unicode string in fact.

It still isn't, because Python 2.7 is still fully supported by Bottle.

> is recode_unicode needness in public API?

Not anymore. It was, back in the day, because some early Python 3 WSGI servers already decoded to 'utf8' instead if 'latin1'. The WSGO spec was updated later (PEP3333).

> Let's write these docs more clearly?.. :smile:

Sure. Pull requests are welcomed. But keep in mind that the docs should work for both Python 2 and 3 users.

> Couldn't we parse (using input_encoding) headers initially? Then recode_unicode and encoding arguments are needless...

No, unfortunately. The 'latin1' workaround is part of the WSGI spec (PEP3333), and there are good reasons for it. It's still a kind of a hack to pass bytes as unicode and it's certainly debatable if this was a good idea.

**Comment by kuraga** [comment]
Thanks for so detailed answer!

Unfortunately I'm not so familiar with Python 2.x to write documentation...

But now I understand (do I?):

* `get(k)` returns unmodified data,
  * in Python 2.x, `bytes`
  * in Python 3.x, `unicode`/`str`
* `getunicode(k, encoding=None)` returns:
  * in Python 2.x, `unicode` which is decoded to `encoding or self.input_encoding`
  * in Python 3.x, `unicode`/`str`, which:
    *  if `recode_unicode`, encoded to `latin1` and then decoded to `encoding or self.input_encoding`),
    * else, unmodified. **BTW, why `encoding` argument [is ignored](https://github.com/bottlepy/bottle/blob/master/bottle.py#L2190-L2196) this case?**

**Comment by defnull** [comment]
Correct so far.

The 'encoding' parameter is ignored in this specific case because the user explicitly asked us to not do any re-encoding (`recode_unicode=False`). We could raise an exception here, stating that the encoding parameter is ignored in this mode of operation, but then again `recode_unicode=False` is kind of useless today anyway and no one should actually need to do that anymore. It's a good candidate for a deprecation warning.

**Comment by kuraga** [comment]
But in Python 2.x, the `encoding` argument is used even if `recode_unicode` is `False`, [isn't it](https://github.com/bottlepy/bottle/blob/master/bottle.py#L2193-L2194)?

**Comment by defnull** [comment]
It's the other way around: In Python 2, the `recode_unicode` setting is ignored, because there is no unicode to be re-encoded. Just bytes that are decoded.

**Comment by kuraga** [comment]
@defnull but:

if `recode_unicode` is `False`, then `getunicode(k, encoding='some_enc')` returns:
* in Python 2.x, `unicode` in some_enc encoding,
* in Python 3.x, `unicode` in original encoding.

Am I correct here? If yes, is this different behavior for different Pythons?

**Comment by kuraga** [comment]
Ok, but no one knows about these reading documentation first :smile: 

Last question.

> Again, you only set `recode_unicode=False` if you are running Python 3 with a non-standard conform WSGI server that already decodes using the final charset even if the WSGI spec forbids it.

If so, why not to unify Python 2.x and Python 3.x behaviors in *this* case:

> if `recode_unicode` is `False`, then `getunicode(k, encoding='some_enc')` returns:
> * in Python 2.x, `unicode` in some_enc encoding,
> * in Python 3.x, `unicode`/`str` in original encoding.

to
> if `recode_unicode` is `False`, then `getunicode(k, encoding='some_enc')` returns `unicode`/`str` in original encoding.

**Comment by defnull** [comment]
Because in Python 2, there is no 'original encoding'. In python 2, the source data is bytes, not unicode, and returning byte strings from a function called `getunicode()` would be kinda misleading ;)

**Comment by kuraga** [comment]
Ahahah... :smile:
